### ISSUE TITLE
google-oauth-client-jetty incompatible with Jetty 9.4+

### ISSUE THREAD

**Issue by lagivan** [googleapis/google-oauth-java-client#397]
#### Environment details

1. Specify the API at the beginning of the title - this is generic, related to OAuth and Jetty.
2. OS type and version: MacOS 10.15.1
3. Java version: jdk1.8.0_191
4. google-oauth-client version(s): 1.30.4

#### Steps to reproduce

  1. Upgrade from 1.30.3 to 1.30.4.
  2. Run the code below - GoogleCredentialHelper.getInstance(someScopes).authorize();

#### Code example

```java
    private static final String CREDENTIAL_FILEPATH = "/credentials/credentials.json";
    private static final java.io.File DATA_STORE_DIR = new java.io.File(
            System.getProperty("user.home"), ".credentials/template");
    private FileDataStoreFactory dataStoreFactory;
    private final JsonFactory jsonFactory;
    private HttpTransport httpTransport;
    private List<String> scopes;

    private GoogleCredentialHelper(List<String> scopes) {
        this.jsonFactory = JacksonFactory.getDefaultInstance();
        try {
            this.httpTransport = GoogleNetHttpTransport.newTrustedTransport();
            this.dataStoreFactory = new FileDataStoreFactory(DATA_STORE_DIR);
            this.scopes = scopes;
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(-1);
        }
    }

    private Credential authorize() throws IOException {
        InputStream in = GoogleCredentialHelper.class.getResourceAsStream(CREDENTIAL_FILEPATH);
        GoogleClientSecrets clientSecrets = GoogleClientSecrets.load(
                jsonFactory, new InputStreamReader(in)
        );

        GoogleAuthorizationCodeFlow flow =
                new GoogleAuthorizationCodeFlow.Builder(
                        httpTransport, jsonFactory, clientSecrets, scopes)
                        .setDataStoreFactory(dataStoreFactory)
                        .setAccessType("offline")
                        .build();
        Credential credential = new AuthorizationCodeInstalledApp(
                flow, new LocalServerReceiver()).authorize("user");
        return credential;
    }

    public static GoogleCredentialHelper getInstance(List<String> scopes) {
        if (instance == null) {
            instance = new GoogleCredentialHelper(scopes);
        }
        return instance;
    }
```

#### Stack trace
```
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Connector.setHost(Ljava/lang/String;)V

	at com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver.getRedirectUri(LocalServerReceiver.java:120)
	at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:121)
	at com.project.gapps.GoogleCredentialHelper.authorize(GoogleCredentialHelper.java:68)
```

#### Any additional information below
The issue appeared after upgrading from 1.30.3 to 1.30.4. Most likely related to the upgrade of Jetty to 8.2 in the latest version.
```
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client-jetty</artifactId>
            <version>1.30.4</version>
        </dependency>
```
The exception appears when credentials are not saved yet - user has to grant permissions via browser.

**Comment by knoppixmeister** [comment]
using of LocalServerReceiver.Builder class instead of "plain" new LocalServerReceiver object could be like workaround

Credential credential = new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver.Builder().setPort(8082).build()).authorize("user");

**Comment by Ancient123** [comment]
@lagivan : Sorry for breaking things 😞

**Comment by ncaq** [comment]
> using of LocalServerReceiver.Builder class instead of "plain" new LocalServerReceiver object could be like workaround
> 
> `Credential credential = new AuthorizationCodeInstalledApp(flow, new LocalServerReceiver.Builder().setPort(8082).build()).authorize("user");`

I use Builder class.
I got the same error.

**Comment by SquaredCanine** [comment]
I have the same error.

**Comment by ncaq** [comment]
Workaround(for some people)

I want to jetty of eclipse version.
Because, I write to sbt below.

~~~scala
"com.google.oauth-client"   % "google-oauth-client-jetty"  % "1.30.3" exclude ("org.mortbay.jetty", "servlet-api"),
~~~

[google-oauth-client-jettyとjetty-serverのバージョンコンフリクトを解決する - ncaq](https://www.ncaq.net/2020/01/10/18/20/43/)

**Comment by ericraskin** [comment]
One more vote for this issue to be resolved.  I have an application that loads 9.4 Jetty server version, which is incompatible with 8.2.  Can this library be updated to work with 9.4?

**Comment by YuanWenqing** [comment]
Same problem!
When will the hotfix version be released?
I'm looking forward to it.

**Comment by ericraskin** [comment]
I downloaded the code, fixed it and installed it in a local Maven repository.  I don't know how to distribute it or get the maintainers to take my change, though.  If anybody knows what to do, I'm happy to send the change.

**Comment by YuanWenqing** [comment]
@ericraskin take a look at the contributing guide: https://github.com/googleapis/google-oauth-java-client/blob/master/CONTRIBUTING.md

**Comment by ericraskin** [comment]
@YuanWenqing I have attempted to contribute the change, but being new I probably did not do it correctly.  The original comment was "I'm not sure this is an upgrade we want." with no further explanation.  I have tried again.  We'll see if they accept it.

**Comment by chingor13** [comment]
We are considering the possibility of providing a separate jetty9 compatible artifact, however, this is a may introduce a dependency management issue for us across our library ecosystem.

Also note that the jetty extensions are not an integral part of the oauth library and are relatively simple adapters/examples of implementing callback handlers for the oauth flow.

**Comment by Seedoorf** [comment]
I downgraded to 1.22.0, it works for me
 	```
<dependency>
  <groupId>com.google.oauth-client</groupId>
  <artifactId>google-oauth-client-jetty</artifactId>
  <version>1.22.0</version>
</dependency>
```

**Comment by shirishjambhorkar** [comment]
Google has fixed the issue in latest jars.
1.30.6 is working for me.

<dependency>
  <groupId>com.google.oauth-client</groupId>
  <artifactId>google-oauth-client-jetty</artifactId>
  <version>1.30.6</version>
</dependency>

**Comment by Shahzaibahmad97** [comment]
> I downgraded to 1.22.0, it works for me
> 
> ```
> <dependency>
>   <groupId>com.google.oauth-client</groupId>
>   <artifactId>google-oauth-client-jetty</artifactId>
>   <version>1.22.0</version>
> </dependency>
> ```

This worked for me with JDK 16.
